Support rehashing of `general::commit_interval`
atheme/atheme pull request #767
Opened 2021-02-28 00:42 UTC by aaronmdjones

2021-02-28 14:23 UTC, ilbelkyr requested changes
Other than the inline comment above, this looks good and happens to fix a bug where the `operserv/readonly` module didn't actually appear to stop periodic database writes at all.

2021-02-28 14:23 UTC, ilbelkyr commented on modules/operserv/readonly.c
> +		                                         config_options.commit_interval);
This doesn't check if `db_save` is set, thus scheduling a null pointer dereference if running without a write-capable backend.

Arguably, the `READONLY` command ought to fail early in that case (similar to the check added in `operserv/set_commitinterval`) – there's little point toggling database writes when they are impossible anyway.

2021-02-28 16:40 UTC, ilbelkyr requested changes
This should be fine, but we'll need to bikeshed the appropriate faultcode used if there's no suitable `db_write`

2021-02-28 16:40 UTC, ilbelkyr commented on modules/operserv/set_commitinterval.c
> +		(void) command_fail(si, fault_badparams, _("You have no write-capable database backend loaded."));
`fault_badparams` doesn't seem right here, though I'm not sure what the best choice would be tbh

2021-02-28 16:40 UTC, ilbelkyr commented on modules/operserv/readonly.c
> +		(void) command_fail(si, fault_badparams, _("You have no write-capable database backend loaded."));
(see other `fault_badparams` comment)

2021-02-28 16:49 UTC, aaronmdjones commented
Perhaps `fault_unimplemented`?

2021-02-28 17:05 UTC, ilbelkyr commented
Either that or `fault_internalerror`, although that one feels like more of a "things went wrong and it's our/the network's fault" kind of thing.

I suppose `fault_unimplemented` was originally meant for things that are supposed to work but aren't implemented, indicating an issue with the implementation – we barely make use of it as it is, though; the current uses of it include:

- `gameserv/dice` running across a math operator it doesn't know. (Feels like *that* should be `fault_badparams` instead, tbh)
- `chanserv/access` trying to modify founder status of a role. That one might be arguable?
- `contrib/cs_access_alias` failing to find the `FLAGS` command to fall back to. That one probably should have a proper dependency, and `fault_internalerror` if it somehow fails anyway.
- `scripting/perl` on an "unexpected error". I feel that ought to be `fault_internalerror`.
- `scripting/perl` failing to provide help because "Perl help commands [are] not yet implemented". Okay, that's the poster child, I guess.
- `transport/jsonrpc`, `transport/xmlrpc` when a command doesn't send a reply via the proper functions. Not sure it's a good fit here, either.

Granted, this isn't really the right issue to take apart questionably defined fault codes and we should look into that another time, perhaps.

2021-03-13 20:54 UTC, ilbelkyr commented
@aaronmdjones let's go with `fault_unimplemented` for now and we can sort through the other thoughts I mentioned at a separate point, maybe?

2021-03-22 02:49 UTC, ilbelkyr approved these changes

2021-09-19 17:05 UTC, merged