Make VERIFY EMAILCHG confirm the account if necessary
atheme/atheme pull request #790
Opened 2021-06-19 15:17 UTC by edk0

Currently you can verify an email address change on an unconfirmed account, but it won't confirm the account even though you've just proved that you own its current email address. Everyone I've spoken to about this thinks it's a bug, so here's a fix.

I've also changed the log message to identify the target of the verify, rather than repeating the name of the requestor; morally that should be its own PR, but it would have had a conflict with this one.

2021-06-19 18:50 UTC, aaronmdjones commented
I've already separately fixed this a few weeks ago, including your log message change and making it a cmdtree so that other modules can add more `VERIFY` subcommands. It's awaiting a review from @ilbelkyr

2021-06-19 19:19 UTC, edk0 commented
oops

2021-06-19 19:33 UTC, aaronmdjones requested changes
No worries. I can merge this right now and still carry on with my new version in a bit when they return. It was she who wanted the cmdtree thing anyway. First, though, I'll need you to make the following change, otherwise it will produce duplicate output.

2021-06-19 19:33 UTC, aaronmdjones commented on modules/nickserv/verify.c
>  			command_success_nodata(si, _("\2%s\2 has now been verified."), mu->email);
Please remove this line.

2021-06-19 19:35 UTC, aaronmdjones commented on modules/nickserv/verify.c
>  		command_success_nodata(si, _("\2%s\2 has now been verified."), mu->email);
And this one.

2021-06-19 19:53 UTC, edk0 commented
I left those in on purpose since two lines reflect different things -- one's about the email address and the other is about the account. But if we don't want that I think they'd need to be wrapped in an else rather than just going away completely?

2021-06-19 20:00 UTC, aaronmdjones commented
Hmm. In my version, I just log the email address, e.g. an unconditional:

```C
command_success_nodata(si, _("\2%s\2 has now been verified."), mu->email);
```

... because it is the e-mail address you're verifying control over either way.

2021-07-02 18:05 UTC, edk0 commented
Hmm. I think I'd like to be explicit that they're verifying both things (and it would make sense that everyone gets to see the thank you message once, too), but maybe we could roll them up into a single message?

2021-07-03 16:22 UTC, aaronmdjones commented
I will merge this as-is and rebase my work on it. I'll also make mine state the account name and e-mail in the same message.

2021-07-03 16:22 UTC, merged