don't just ignore invalid CS LIST criteria/parameters
atheme/atheme pull request #816
Opened 2021-08-14 16:47 UTC by jesopo

I'm certain there's going to be something about how I chose to pass the information back from `process_parvarray()` that isn't right, but it works!

closes #801

2021-08-14 17:00 UTC, jesopo commented
```
16:59 <jess> list a
16:59 -ChanServ(ChanServ@services.int)- Error: a is not a valid LIST option
16:59 <jess> list pattern
16:59 -ChanServ(ChanServ@services.int)- Error: Invalid argument for option pattern
16:59 <jess> list pattern * a
16:59 -ChanServ(ChanServ@services.int)- Error: a is not a valid LIST option
16:59 <jess> list pattern *
16:59 -ChanServ(ChanServ@services.int)- Channels matching pattern * :
16:59 -ChanServ(ChanServ@services.int)- No channel matched criteria pattern *
```

2021-09-18 02:04 UTC, glguy commented
You'll need to add your success enum case to your result type, currently `0` has two meanings, it's either the first error or success.

```
➜  ~ cat test.c
#include <stdio.h>
enum list_opterr { OPTERR_UNKNOWN_OPT, OPTERR_BAD_ARG, };
int main(void) {
        printf("OPTERR_UNKNOWN_OPT (%d)\n", OPTERR_UNKNOWN_OPT);
        printf("OPTERR_BAD_ARG (%d)\n", OPTERR_BAD_ARG);
}
➜  ~ clang test.c -o test && ./test
OPTERR_UNKNOWN_OPT (0)
OPTERR_BAD_ARG (1)
```

something like

```c
enum list_result
{
	OPTSUCCESS,
	OPTERR_UNKNOWN_OPT,
	OPTERR_BAD_ARG,
};

static enum list_result
process_parvarray(const struct list_option *opts, size_t optsize, int parc, char *parv[], char **opt_last)
```

2021-12-01 22:03 UTC, jesopo commented
@glguy looking better?

2022-09-27 18:39 UTC, dwfreed requested changes

2022-09-27 18:39 UTC, dwfreed commented on modules/chanserv/list.c
> +static unsigned int
```suggestion
static enum list_opterr
```

Since you only return enum values, the return type should be the enum.

2022-09-27 18:39 UTC, dwfreed commented on modules/chanserv/list.c
> +	unsigned int parv_err = process_parvarray(optstable, ARRAY_SIZE(optstable), parc, parv, &opt_last);
```suggestion
	enum list_opterr parv_err = process_parvarray(optstable, ARRAY_SIZE(optstable), parc, parv, &opt_last);
```

Likewise

2022-10-04 18:15 UTC, aaronmdjones approved these changes

2022-10-04 18:16 UTC, aaronmdjones commented
`opt_last` is uninitialised if the function returns no error, but the caller does not use its value in that case anyway, so that's okay.

2022-10-04 18:16 UTC, merged