log account name, rather than provided target, in multimark
atheme/atheme pull request #868
Opened 2022-04-30 18:08 UTC by jesopo

(apologies for changing some stuff to `const` while i was in the neighbourhood)

2022-04-30 18:54 UTC, jesopo commented
the problem being solved here is
```
/ns mark =person add bad person
```
logs as
```
<@NickServ> jess MARK:ADD: =person bad person
```
which is not great for log grepping

2022-04-30 21:56 UTC, dwfreed requested changes

2022-04-30 21:56 UTC, dwfreed commented on modules/nickserv/multimark.c
> +	target = entity(mu)->name;
This will null-deref if you want to list the marks of a dropped account

2022-05-01 14:45 UTC, aaronmdjones approved these changes

2022-05-01 14:45 UTC, merged